In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
anime = pd.read_csv('anime.csv')

In [3]:
anime.head()

,anime_id,Name,Score,Genres
0,1,Cowboy Bebop,8.78,"Action, Adventure, Comedy, Drama, Sci-Fi, Space"
1,5,Cowboy Bebop: Tengoku no Tobira,8.39,"Action, Drama, Mystery, Sci-Fi, Space"
2,6,Trigun,8.24,"Action, Sci-Fi, Adventure, Comedy, Drama, Shounen"
3,7,Witch Hunter Robin,7.27,"Action, Mystery, Police, Supernatural, Drama, ..."
4,8,Bouken Ou Beet,6.98,"Adventure, Fantasy, Shounen, Supernatural"

In [4]:
anime.shape

(16214, 4)

In [5]:
users = pd.read_csv('user.csv')

In [6]:
users.head()

   user_id  anime_id  rating  watching_status  watched_episodes
0        0        67       9                1                 1
1        0      6702       7                1                 4
2        0       242      10                1                 4
3        0      4898       0                1                 1
4        0        21      10                1                 0

In [7]:
users.shape

(109224747, 5)

In [8]:
ratings = pd.read_csv('rating.csv')

In [9]:
ratings.head()

   user_id  anime_id  rating
0        0       430       9
1        0      1004       5
2        0      3010       7
3        0       570       7
4        0      2762       9

In [10]:
ratings.shape

(57633278, 3)

In [11]:
print(anime.shape)
print(users.shape)
print(ratings.shape)

(16214, 4)
(109224747, 5)
(57633278, 3)

In [12]:
ratings['user_id'].value_counts()

189037    15455
162615    14864
68042     13462
283786    12778
259790     9996
          ...
201316        1
201300        1
97555         1
201293        1
137466        1
Name: user_id, Length: 310059, dtype: int64

In [13]:
ratings['user_id'].unique().shape

(310059,)

In [14]:
x = ratings['user_id'].value_counts() > 500

In [15]:
x[x].shape

(22903,)

In [16]:
y = x[x].index

In [17]:
y

Int64Index([189037, 162615,  68042, 283786, 259790, 291207, 182280, 277841,
            336459,  10255,
            ...
             61222, 121484,  78996, 207917,  88147, 233887, 239706, 118977,
             94338, 293779],
           dtype='int64', length=22903)

In [18]:
ratings = ratings[ratings['user_id'].isin(y)]

In [19]:
ratings.head()

      user_id  anime_id  rating
1683       17      5781       7
1684       17      6682      10
1685       17     14199       2
1686       17     12355       6
1687       17     23673       6

In [20]:
ratings.shape

(19048102, 3)

In [21]:
ratings_with_anime = ratings.merge(anime, on = "anime_id")

In [22]:
ratings_with_anime.head()

,user_id,anime_id,rating,Name,Score,Genres
0,17,5781,7,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ..."
1,286,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ..."
2,314,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ..."
3,326,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ..."
4,389,5781,4,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ..."

In [23]:
ratings_with_anime.shape

(18540227, 6)

In [24]:
num_rating = ratings_with_anime.groupby('Name')['Score'].count().reset_index()

In [25]:
num_rating.head()

                                                Name  Score
0                                                "0"    591
1  "Aesop" no Ohanashi yori: Ushi to Kaeru, Yokub...     14
2          "Bungaku Shoujo" Kyou no Oyatsu: Hatsukoi   2704
3                           "Bungaku Shoujo" Memoire   2911
4                             "Bungaku Shoujo" Movie   4464

In [26]:
num_rating.rename(columns={'Score':'num_of_rating'}, inplace=True)

In [27]:
num_rating.head()

                                                Name  num_of_rating
0                                                "0"            591
1  "Aesop" no Ohanashi yori: Ushi to Kaeru, Yokub...             14
2          "Bungaku Shoujo" Kyou no Oyatsu: Hatsukoi           2704
3                           "Bungaku Shoujo" Memoire           2911
4                             "Bungaku Shoujo" Movie           4464

In [28]:
final_rating = ratings_with_anime.merge(num_rating, on= 'Name')

In [29]:
final_rating.head()

,user_id,anime_id,rating,Name,Score,Genres,num_of_rating
0,17,5781,7,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
1,286,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
2,314,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
3,326,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
4,389,5781,4,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606

In [30]:
final_rating.shape

(18540227, 7)

In [31]:
final_rating[final_rating['num_of_rating']>=10000]

,user_id,anime_id,rating,Name,Score,Genres,num_of_rating
21991,17,12355,6,Ookami Kodomo no Ame to Yuki,8.64,"Fantasy, Slice of Life",11991
21992,19,12355,8,Ookami Kodomo no Ame to Yuki,8.64,"Fantasy, Slice of Life",11991
21993,111,12355,9,Ookami Kodomo no Ame to Yuki,8.64,"Fantasy, Slice of Life",11991
21994,112,12355,9,Ookami Kodomo no Ame to Yuki,8.64,"Fantasy, Slice of Life",11991
21995,156,12355,7,Ookami Kodomo no Ame to Yuki,8.64,"Fantasy, Slice of Life",11991
...,...,...,...,...,...,...,...
13623990,353255,21855,8,Hanamonogatari,7.99,"Mystery, Comedy, Supernatural",10285
13623991,353304,21855,6,Hanamonogatari,7.99,"Mystery, Comedy, Supernatural",10285
13623992,353318,21855,9,Hanamonogatari,7.99,"Mystery, Comedy, Supernatural",10285
13623993,353326,21855,8,Hanamonogatari,7.99,"Mystery, Comedy, Supernatural",10285
13623994,353365,21855,10,Hanamonogatari,7.99,"Mystery, Comedy, Supernatural",10285

In [32]:
final_rating.sample()

,user_id,anime_id,rating,Name,Score,Genres,num_of_rating
586987,351336,30240,9,Prison School,7.71,"Comedy, Ecchi, Romance, School, Seinen",12587

In [33]:
final_rating.shape

(18540227, 7)

In [34]:
final_rating.drop_duplicates(['user_id','Name'], inplace= True)

In [35]:
final_rating.shape

(18540211, 7)

In [36]:
final_rating

,user_id,anime_id,rating,Name,Score,Genres,num_of_rating
0,17,5781,7,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
1,286,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
2,314,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
3,326,5781,10,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
4,389,5781,4,Isekai no Seikishi Monogatari,7.84,"Action, Comedy, Ecchi, Fantasy, Harem, Mecha, ...",5606
...,...,...,...,...,...,...,...
18540222,283786,45448,6,Dou Hun Wei Zhi Xuan Yue Qiyuan IV,Unknown,"Action, Fantasy",1
18540223,283786,42465,6,Guan Hai Ce Zhi Tie Qi Xiong Guan,Unknown,"Action, Military, Historical, Martial Arts, Fa...",1
18540224,289506,41277,4,Rainbow Ruby,Unknown,"Kids, Fantasy",1
18540225,308285,40389,8,Uchuu Senkan Yamato 2205: Aratanaru Tabidachi,Unknown,"Action, Military, Sci-Fi, Space, Drama",1
18540226,347134,39627,5,Nan-chan no Koutsuu Anzen,Unknown,Kids,1

In [37]:
anime_pivot = final_rating.pivot_table(columns='user_id', index='Name', values= 'rating')

In [38]:
anime_pivot

user_id,17,19,42,111,112,146,156,172,198,222,...,353300,353304,353311,353318,353325,353326,353328,353365,353395,353398
Name,,,,,,,,,,,,,,,,,,,,,
"""0""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Aesop"" no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Bungaku Shoujo"" Kyou no Oyatsu: Hatsukoi",NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Bungaku Shoujo"" Memoire",NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"""Bungaku Shoujo"" Movie",NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xxxHOLiC Rou,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
xxxHOLiC Shunmuki,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,...,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN
Üks Uks,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ēlDLIVE,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,8.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
◯,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN

In [39]:
anime_pivot.shape

(15531, 22902)

In [40]:
anime_pivot.fillna(0, inplace=True)

In [41]:
anime_pivot

user_id,17,19,42,111,112,146,156,172,198,222,...,353300,353304,353311,353318,353325,353326,353328,353365,353395,353398
Name,,,,,,,,,,,,,,,,,,,,,
"""0""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"""Aesop"" no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"""Bungaku Shoujo"" Kyou no Oyatsu: Hatsukoi",0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"""Bungaku Shoujo"" Memoire",0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"""Bungaku Shoujo"" Movie",0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,...,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
xxxHOLiC Rou,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,...,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0
xxxHOLiC Shunmuki,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,...,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0
Üks Uks,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ēlDLIVE,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
◯,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0

In [42]:
from scipy.sparse import csr_matrix

In [43]:
anime_sparse = csr_matrix(anime_pivot)

In [44]:
anime_sparse

<15531x22902 sparse matrix of type '<class 'numpy.float64'>'
	with 18540211 stored elements in Compressed Sparse Row format>

In [45]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [46]:
model.fit(anime_sparse)

NearestNeighbors(algorithm='brute')

In [47]:
distance, suggestion = model.kneighbors(anime_pivot.iloc[237,:].values.reshape(1,-1), n_neighbors=10)

In [48]:
distance

array([[  0.        , 169.69384196, 170.0088233 , 170.51392905,
        170.55204484, 170.64876208, 170.6839184 , 170.73078223,
        170.76592166, 170.78641632]])

In [49]:
suggestion

array([[  237,   236, 12290, 13016, 14595,  6539,  4584,  1612,  9006,
        12289]], dtype=int64)

In [50]:
for i in range(len(suggestion)):
    print(anime_pivot.index[suggestion[i]])

Index(['Africa no Salaryman (TV)', 'Africa no Salaryman',
       'Shounen Ashibe: Go! Go! Goma-chan 4',
       'TV Yarou Nanaana: Kaibutsu Kraken wo Oe!', 'Watanuki-san Chi no',
       'Kedama no Gonjirou', 'Hakushon Daimaou 2020', 'Business Fish',
       'Motto! Majime ni Fumajime Kaiketsu Zorori',
       'Shounen Ashibe: Go! Go! Goma-chan 3'],
      dtype='object', name='Name')

In [51]:
anime_pivot.index[3]

'"Bungaku Shoujo" Memoire'

In [52]:
anime_pivot.index

Index(['"0"', '"Aesop" no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu',
       '"Bungaku Shoujo" Kyou no Oyatsu: Hatsukoi', '"Bungaku Shoujo" Memoire',
       '"Bungaku Shoujo" Movie', '"Calpis" Hakkou Monogatari', '"Eiji"',
       '"Eikou Naki Tensai-tachi" Kara no Monogatari', '"Eiyuu" Kaitai',
       '"Kinako" Movie x Mameshiba',
       ...
       's.CRY.ed Alteration II: Quan', 'the FLY BanD!', 'xxxHOLiC',
       'xxxHOLiC Kei', 'xxxHOLiC Movie: Manatsu no Yoru no Yume',
       'xxxHOLiC Rou', 'xxxHOLiC Shunmuki', 'Üks Uks', 'ēlDLIVE', '◯'],
      dtype='object', name='Name', length=15531)

In [53]:
anime_name = anime_pivot.index

In [54]:
import pickle
pickle.dump(model, open('artifacts/model.pkl', 'wb'))
pickle.dump(anime_name, open('artifacts/anime_name.pkl', 'wb'))
pickle.dump(final_rating, open('artifacts/final_rating.pkl', 'wb'))
pickle.dump(anime_pivot, open('artifacts/anime_pivot.pkl', 'wb'))

In [55]:
def recommend_anime(anime_name):
    anime_id = np.where(anime_pivot.index == anime_name)[0][0]
    distance, suggestion = model.kneighbors(anime_pivot.iloc[anime_id,:].values.reshape(1,-1), n_neighbors=6 )
    
    for i in range(len(suggestion)):
            anime = anime_pivot.index[suggestion[i]]
            for j in anime:
                if j == anime_name:
                    print(f"You searched '{anime_name}'\n")
                    print("The suggestion anime are: \n")
                else:
                    print(j)

In [56]:
anime_name= 'Naruto'
recommend_anime(anime_name)

You searched 'Naruto'

The suggestion anime are:

Naruto: Shippuuden
Bleach
Ao no Exorcist
Naruto Movie 1: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo!
Naruto: Shippuuden Movie 1

In [57]:
import numpy as np

def recommend_anime_with_confidence(anime_name):
    anime_id = np.where(anime_pivot.index == anime_name)[0][0]
    distances, suggestions = model.kneighbors(anime_pivot.iloc[anime_id,:].values.reshape(1,-1), n_neighbors=6 )

    print(f"You searched '{anime_name}'\n")
    print("The suggested anime and their confidence levels are: \n")
    for distance, suggestion in zip(distances.flatten(), suggestions.flatten()):
        suggested_anime = anime_pivot.index[suggestion]
        confidence_level = 1 / (1 + distance)  # Calculating confidence level
        print(f"Anime: {suggested_anime}, Confidence Level: {confidence_level:.10f}")

anime_name= 'Naruto'
recommend_anime_with_confidence(anime_name)

You searched 'Naruto'

The suggested anime and their confidence levels are:

Anime: Naruto, Confidence Level: 1.0000000000
Anime: Naruto: Shippuuden, Confidence Level: 0.0016023148
Anime: Bleach, Confidence Level: 0.0015321639
Anime: Ao no Exorcist, Confidence Level: 0.0014788849
Anime: Naruto Movie 1: Dai Katsugeki!! Yuki Hime Shinobu Houjou Dattebayo!, Confidence Level: 0.0014552737
Anime: Naruto: Shippuuden Movie 1, Confidence Level: 0.0014530350